-- CUSTOMERS

INSERT ALL
INTO customers(customer_id, first_name, last_name, email, region, signup_date, customer_tier)
VALUES(1, 'Sarah', 'Diana', 'sarah@gmail.com','North America', TO_DATE('2024-01-15','YYYY-MM-DD'),'Premium')
INTO customers(customer_id, first_name, last_name, email, region, signup_date, customer_tier)
VALUES(2, 'John', 'Smith', 'johnsmith250@gmail.com','North America', TO_DATE('2024-02-13','YYYY-MM-DD'),'Standard')
INTO customers(customer_id, first_name, last_name, email, region, signup_date, customer_tier)
VALUES(3, 'Michael', 'Brown', 'michael@gmail.com','North America', TO_DATE('2024-03-10','YYYY-MM-DD'),'Premium')
INTO customers(customer_id, first_name, last_name, email, region, signup_date, customer_tier)
VALUES(4, 'David', 'Wilson', 'david@gmail.com','North America', TO_DATE('2024-04-12','YYYY-MM-DD'),'Standard')
INTO customers(customer_id, first_name, last_name, email, region, signup_date, customer_tier)
VALUES(5, 'Emily', 'Davis', 'emily@gmail.com','North America', TO_DATE('2024-05-15','YYYY-MM-DD'),'Standard')
INTO customers(customer_id, first_name, last_name, email, region, signup_date, customer_tier)
VALUES(6, 'Maria', 'Garcia', 'maria@gmail.com','Europe', TO_DATE('2024-02-15','YYYY-MM-DD'),'Premium')
INTO customers(customer_id, first_name, last_name, email, region, signup_date, customer_tier)
VALUES(7, 'Mike', 'Miller', 'mike@gmail.com','Europe', TO_DATE('2024-03-25','YYYY-MM-DD'),'Standard')
INTO customers(customer_id, first_name, last_name, email, region, signup_date, customer_tier)
VALUES(8, 'Emma', 'Jones', 'emma@gmail.com','Europe', TO_DATE('2024-01-05','YYYY-MM-DD'),'Standard')
INTO customers(customer_id, first_name, last_name, email, region, signup_date, customer_tier)
VALUES(9, 'Taylor', 'Robert', 'taylor@gmail.com','Europe', TO_DATE('2024-04-05','YYYY-MM-DD'),'Premium')
INTO customers(customer_id, first_name, last_name, email, region, signup_date, customer_tier)
VALUES(10, 'Sophia', 'Anderson', 'sophia@gmail.com','Europe', TO_DATE('2024-02-26','YYYY-MM-DD'),'Standard')
INTO customers(customer_id, first_name, last_name, email, region, signup_date, customer_tier)
VALUES(11, 'William', 'Thomas', 'william@gmail.com','Asia', TO_DATE('2024-03-05','YYYY-MM-DD'),'Premium')
INTO customers(customer_id, first_name, last_name, email, region, signup_date, customer_tier)
VALUES(12, 'Olivia', 'Jackson', 'olivia@gmail.com','Asia', TO_DATE('2024-01-25','YYYY-MM-DD'),'Standard')
INTO customers(customer_id, first_name, last_name, email, region, signup_date, customer_tier)
VALUES(13, 'Daniel', 'White', 'daniel@gmail.com','Asia', TO_DATE('2024-02-10','YYYY-MM-DD'),'Standard')
INTO customers(customer_id, first_name, last_name, email, region, signup_date, customer_tier)
VALUES(14, 'Ava', 'Harris', 'eva@gmail.com','Asia', TO_DATE('2024-03-18','YYYY-MM-DD'),'Premium')
INTO customers(customer_id, first_name, last_name, email, region, signup_date, customer_tier)
VALUES(15, 'Joseph', 'Martin', 'joseph@gmail.com','Asia', TO_DATE('2024-04-01','YYYY-MM-DD'),'Standard')
INTO customers(customer_id, first_name, last_name, email, region, signup_date, customer_tier)
VALUES(16, 'Noah', 'Thompson', 'noah@gmail.com','Africa', TO_DATE('2024-04-02','YYYY-MM-DD'),'Standard')
INTO customers(customer_id, first_name, last_name, email, region, signup_date, customer_tier)
VALUES(17, 'Isabella', 'Moore', 'isabella@gmail.com','Africa', TO_DATE('2024-05-02','YYYY-MM-DD'),'Standard')
INTO customers(customer_id, first_name, last_name, email, region, signup_date, customer_tier)
VALUES(18, 'Rukara', 'Jan', 'rukara@gmail.com','Africa', TO_DATE('2024-06-12','YYYY-MM-DD'),'Standard')
INTO customers(customer_id, first_name, last_name, email, region, signup_date, customer_tier)
VALUES(19, 'Mumberendombe', 'Kavaga', 'mumberendombe@gmail.com','Africa', TO_DATE('2024-07-22','YYYY-MM-DD'),'Standard')
INTO customers(customer_id, first_name, last_name, email, region, signup_date, customer_tier)
VALUES(20, 'Mohammad', 'Amir', 'mohammd@gmail.com','Africa', TO_DATE('2024-08-13','YYYY-MM-DD'),'Standard')
INTO customers(customer_id, first_name, last_name, email, region, signup_date, customer_tier)
VALUES(21, 'Pop', 'Smoke', 'pop@gmail.com','North America', TO_DATE('2024-09-02','YYYY-MM-DD'),'Standard')
INTO customers(customer_id, first_name, last_name, email, region, signup_date, customer_tier)
VALUES(22, 'Billie', 'Jean', 'billie@gmail.com','Europe', TO_DATE('2024-04-11','YYYY-MM-DD'),'Standard')
INTO customers(customer_id, first_name, last_name, email, region, signup_date, customer_tier)
VALUES(23, 'Ethan', 'Lee', 'ethan@gmail.com','Asia', TO_DATE('2024-05-02','YYYY-MM-DD'),'Standard')
INTO customers(customer_id, first_name, last_name, email, region, signup_date, customer_tier)
VALUES(24, 'Kigeli', 'Francois', 'kigeli@gmail.com','Africa', TO_DATE('2024-07-22','YYYY-MM-DD'),'Standard')
SELECT * FROM dual;

-- PRODUCTS

INSERT ALL
INTO products(product_id, product_name, category, price, cost, stock_quantity)
VALUES(1, 'Smartphone X', 'Electronics', 899.99, 450.00, 50)
INTO products(product_id, product_name, category, price, cost, stock_quantity)
VALUES(2, 'Laptop Pro', 'Electronics', 1299.99, 700.00, 30)
INTO products(product_id, product_name, category, price, cost, stock_quantity)
VALUES(3, 'Wireless Earbuds', 'Electronics', 199.99, 80.00, 100)
INTO products(product_id, product_name, category, price, cost, stock_quantity)
VALUES(4, 'Smart Watch', 'Electronics', 299.99, 150.00, 75)
INTO products(product_id, product_name, category, price, cost, stock_quantity)
VALUES(5, 'Table Air', 'Electronics', 499.99, 250.00, 40)
INTO products(product_id, product_name, category, price, cost, stock_quantity)
VALUES(6, 'Coffee Maker', 'Home Appliances', 89.99, 40.00, 60)
INTO products(product_id, product_name, category, price, cost, stock_quantity)
VALUES(7, 'Blender Pro', 'Home Appliances', 129.99, 60.00, 45)
INTO products(product_id, product_name, category, price, cost, stock_quantity)
VALUES(8, 'Air Purifier', 'Home Appliances', 199.99, 90.00, 25)
INTO products(product_id, product_name, category, price, cost, stock_quantity)
VALUES(9, 'Robot Vacuum', 'Home Appliances', 349.99, 180.00, 20)
INTO products(product_id, product_name, category, price, cost, stock_quantity)
VALUES(10, 'Microwave Oven', 'Home Appliances', 159.99, 75.00, 35)
INTO products(product_id, product_name, category, price, cost, stock_quantity)
VALUES(11, 'Database Design', 'Books', 59.99, 20.00, 150)
INTO products(product_id, product_name, category, price, cost, stock_quantity)
VALUES(12, 'SQL Master', 'Books', 49.99, 15.00, 200)
INTO products(product_id, product_name, category, price, cost, stock_quantity)
VALUES(13, 'Data Analytics', 'Books', 69.99, 25.00, 120)
INTO products(product_id, product_name, category, price, cost, stock_quantity)
VALUES(14, 'T-Shirt Classic', 'Clothing', 24.99, 8.00, 300)
INTO products(product_id, product_name, category, price, cost, stock_quantity)
VALUES(15, 'Jeans Regular', 'Clothing', 59.99, 20.00, 150)
INTO products(product_id, product_name, category, price, cost, stock_quantity)
VALUES(16, 'VR Headset', 'Electronics', 399.99, 200.00, 10)
INTO products(product_id, product_name, category, price, cost, stock_quantity)
VALUES(17, 'Gaming Console', 'Electronics', 499.99, 250.00, 15)
INTO products(product_id, product_name, category, price, cost, stock_quantity)
VALUES(18, 'Electric Kettle', 'Home Appliances', 49.99, 22.00, 30)
INTO products(product_id, product_name, category, price, cost, stock_quantity)
VALUES(19, 'Fiction Novel', 'Books', 19.99, 6.00, 100)
INTO products(product_id, product_name, category, price, cost, stock_quantity)
VALUES(20, 'Winter Jacket', 'Clothing', 149.99, 60.00, 25)
SELECT * FROM dual;

-- ORDERS

INSERT ALL
INTO orders(order_id, customer_id, product_id, order_date, quantity, amount, payment_method)
VALUES(1, 1, 1, TO_DATE('2024-01-20','YYYY-MM-DD'), 1, 899.99, 'Credit Card')
INTO orders(order_id, customer_id, product_id, order_date, quantity, amount, payment_method)
VALUES(2, 2, 3, TO_DATE('2024-01-22','YYYY-MM-DD'), 2, 399.98, 'PayPal')
INTO orders(order_id, customer_id, product_id, order_date, quantity, amount, payment_method)
VALUES(3, 3, 2, TO_DATE('2024-01-25','YYYY-MM-DD'), 1, 1299.99, 'Credit Card')
INTO orders(order_id, customer_id, product_id, order_date, quantity, amount, payment_method)
VALUES(4, 4, 6, TO_DATE('2024-01-28','YYYY-MM-DD'), 1, 89.99, 'Debit Card')
INTO orders(order_id, customer_id, product_id, order_date, quantity, amount, payment_method)
VALUES(5, 5, 11, TO_DATE('2024-01-30','YYYY-MM-DD'), 3, 179.97, 'Credit Card')
INTO orders(order_id, customer_id, product_id, order_date, quantity, amount, payment_method)
VALUES(6, 1, 4, TO_DATE('2024-02-05','YYYY-MM-DD'), 1, 299.99, 'Credit Card')
INTO orders(order_id, customer_id, product_id, order_date, quantity, amount, payment_method)
VALUES(7, 2, 5, TO_DATE('2024-02-10','YYYY-MM-DD'), 1, 499.99, 'PayPal')
INTO orders(order_id, customer_id, product_id, order_date, quantity, amount, payment_method)
VALUES(8, 3, 7, TO_DATE('2024-02-12','YYYY-MM-DD'), 2, 259.98, 'Credit Card')
INTO orders(order_id, customer_id, product_id, order_date, quantity, amount, payment_method)
VALUES(9, 4, 9, TO_DATE('2024-02-15','YYYY-MM-DD'), 1, 349.99, 'Debit Card')
INTO orders(order_id, customer_id, product_id, order_date, quantity, amount, payment_method)
VALUES(10, 5, 12, TO_DATE('2024-02-18','YYYY-MM-DD'), 4, 199.96, 'Credit Card')
INTO orders(order_id, customer_id, product_id, order_date, quantity, amount, payment_method)
VALUES(11, 6, 1, TO_DATE('2024-02-20','YYYY-MM-DD'), 1, 899.99, 'Credit Card')
INTO orders(order_id, customer_id, product_id, order_date, quantity, amount, payment_method)
VALUES(12, 7, 3, TO_DATE('2024-02-22','YYYY-MM-DD'), 3, 599.97, 'PayPal')
INTO orders(order_id, customer_id, product_id, order_date, quantity, amount, payment_method)
VALUES(13, 8, 2, TO_DATE('2024-02-25','YYYY-MM-DD'), 1, 1299.99, 'Credit Card')
INTO orders(order_id, customer_id, product_id, order_date, quantity, amount, payment_method)
VALUES(14, 9, 6, TO_DATE('2024-02-26','YYYY-MM-DD'), 2, 179.98, 'Debit Card')
INTO orders(order_id, customer_id, product_id, order_date, quantity, amount, payment_method)
VALUES(15, 10, 11, TO_DATE('2024-02-28','YYYY-MM-DD'), 2, 119.98, 'Credit Card')
INTO orders(order_id, customer_id, product_id, order_date, quantity, amount, payment_method)
VALUES(16, 1, 2, TO_DATE('2024-03-05','YYYY-MM-DD'), 1, 1299.99, 'Credit Card')
INTO orders(order_id, customer_id, product_id, order_date, quantity, amount, payment_method)
VALUES(17, 2, 8, TO_DATE('2024-03-08','YYYY-MM-DD'), 1, 199.99, 'PayPal')
INTO orders(order_id, customer_id, product_id, order_date, quantity, amount, payment_method)
VALUES(18, 3, 10, TO_DATE('2024-03-10','YYYY-MM-DD'), 1, 159.99, 'Credit Card')
INTO orders(order_id, customer_id, product_id, order_date, quantity, amount, payment_method)
VALUES(19, 4, 13, TO_DATE('2024-03-12','YYYY-MM-DD'), 2, 139.98, 'Debit Card')
INTO orders(order_id, customer_id, product_id, order_date, quantity, amount, payment_method)
VALUES(20, 5, 14, TO_DATE('2024-03-15','YYYY-MM-DD'), 5, 124.95, 'Credit Card')
INTO orders(order_id, customer_id, product_id, order_date, quantity, amount, payment_method)
VALUES(21, 6, 4, TO_DATE('2024-03-18','YYYY-MM-DD'), 1, 299.99, 'Credit Card')
INTO orders(order_id, customer_id, product_id, order_date, quantity, amount, payment_method)
VALUES(22, 7, 5, TO_DATE('2024-03-20','YYYY-MM-DD'), 1, 499.99, 'PayPal')
INTO orders(order_id, customer_id, product_id, order_date, quantity, amount, payment_method)
VALUES(23, 8, 7, TO_DATE('2024-03-22','YYYY-MM-DD'), 1, 129.99, 'Credit Card')
INTO orders(order_id, customer_id, product_id, order_date, quantity, amount, payment_method)
VALUES(24, 9, 9, TO_DATE('2024-03-25','YYYY-MM-DD'), 1, 349.99, 'Debit Card')
INTO orders(order_id, customer_id, product_id, order_date, quantity, amount, payment_method)
VALUES(25, 10, 12, TO_DATE('2024-03-28','YYYY-MM-DD'), 3, 149.97, 'Credit Card')
INTO orders(order_id, customer_id, product_id, order_date, quantity, amount, payment_method)
VALUES(26, 11, 1, TO_DATE('2024-03-30','YYYY-MM-DD'), 1, 899.99, 'Credit Card')
INTO orders(order_id, customer_id, product_id, order_date, quantity, amount, payment_method)
VALUES(27, 11, 3, TO_DATE('2024-04-02','YYYY-MM-DD'), 2, 399.98, 'PayPal')
INTO orders(order_id, customer_id, product_id, order_date, quantity, amount, payment_method)
VALUES(28, 12, 2, TO_DATE('2024-04-05','YYYY-MM-DD'), 1, 1299.99, 'Credit Card')
INTO orders(order_id, customer_id, product_id, order_date, quantity, amount, payment_method)
VALUES(29, 13, 6, TO_DATE('2024-04-08','YYYY-MM-DD'), 1, 89.99, 'Debit Card')
INTO orders(order_id, customer_id, product_id, order_date, quantity, amount, payment_method)
VALUES(30, 14, 11, TO_DATE('2024-04-10','YYYY-MM-DD'), 4, 239.96, 'Credit Card')
INTO orders(order_id, customer_id, product_id, order_date, quantity, amount, payment_method)
VALUES(31, 15, 4, TO_DATE('2024-04-12','YYYY-MM-DD'), 1, 299.99, 'Credit Card')
INTO orders(order_id, customer_id, product_id, order_date, quantity, amount, payment_method)
VALUES(32, 1, 15, TO_DATE('2024-04-15','YYYY-MM-DD'), 2, 119.98, 'Credit Card')
INTO orders(order_id, customer_id, product_id, order_date, quantity, amount, payment_method)
VALUES(33, 2, 13, TO_DATE('2024-04-18','YYYY-MM-DD'), 1, 69.99, 'PayPal')
INTO orders(order_id, customer_id, product_id, order_date, quantity, amount, payment_method)
VALUES(34, 3, 10, TO_DATE('2024-04-20','YYYY-MM-DD'), 1, 159.99, 'Credit Card')
INTO orders(order_id, customer_id, product_id, order_date, quantity, amount, payment_method)
VALUES(35, 4, 8, TO_DATE('2024-04-22','YYYY-MM-DD'), 1, 199.99, 'Debit Card')
INTO orders(order_id, customer_id, product_id, order_date, quantity, amount, payment_method)
VALUES(36, 5, 5, TO_DATE('2024-04-25','YYYY-MM-DD'), 1, 499.99, 'Credit Card')
INTO orders(order_id, customer_id, product_id, order_date, quantity, amount, payment_method)
VALUES(37, 1, 3, TO_DATE('2024-04-26','YYYY-MM-DD'), 1, 199.99, 'Credit Card')
INTO orders(order_id, customer_id, product_id, order_date, quantity, amount, payment_method)
VALUES(38, 2, 6, TO_DATE('2024-04-27','YYYY-MM-DD'), 1, 89.99, 'PayPal')
INTO orders(order_id, customer_id, product_id, order_date, quantity, amount, payment_method)
VALUES(39, 3, 11, TO_DATE('2024-04-28','YYYY-MM-DD'), 2, 119.98, 'Credit Card')
INTO orders(order_id, customer_id, product_id, order_date, quantity, amount, payment_method)
VALUES(40, 4, 14, TO_DATE('2024-04-29','YYYY-MM-DD'), 3, 74.97, 'Debit Card')
INTO orders(order_id, customer_id, product_id, order_date, quantity, amount, payment_method)
VALUES(41, 5, 2, TO_DATE('2024-04-30','YYYY-MM-DD'), 1, 1299.99, 'Credit Card')
INTO orders(order_id, customer_id, product_id, order_date, quantity, amount, payment_method)
VALUES(42, 6, 7, TO_DATE('2024-05-01','YYYY-MM-DD'), 1, 129.99, 'Credit Card')
INTO orders(order_id, customer_id, product_id, order_date, quantity, amount, payment_method)
VALUES(43, 7, 9, TO_DATE('2024-05-02','YYYY-MM-DD'), 1, 349.99, 'PayPal')
INTO orders(order_id, customer_id, product_id, order_date, quantity, amount, payment_method)
VALUES(44, 8, 12, TO_DATE('2024-05-03','YYYY-MM-DD'), 2, 99.98, 'Credit Card')
INTO orders(order_id, customer_id, product_id, order_date, quantity, amount, payment_method)
VALUES(45, 9, 1, TO_DATE('2024-05-04','YYYY-MM-DD'), 1, 899.99, 'Debit Card')
INTO orders(order_id, customer_id, product_id, order_date, quantity, amount, payment_method)
VALUES(46, 10, 3, TO_DATE('2024-05-05','YYYY-MM-DD'), 2, 399.98, 'Credit Card')
INTO orders(order_id, customer_id, product_id, order_date, quantity, amount, payment_method)
VALUES(47, 11, 10, TO_DATE('2024-05-06','YYYY-MM-DD'), 1, 159.99, 'Credit Card')
INTO orders(order_id, customer_id, product_id, order_date, quantity, amount, payment_method)
VALUES(48, 12, 11, TO_DATE('2024-05-07','YYYY-MM-DD'), 3, 179.97, 'PayPal')
INTO orders(order_id, customer_id, product_id, order_date, quantity, amount, payment_method)
VALUES(49, 13, 4, TO_DATE('2024-05-08','YYYY-MM-DD'), 1, 299.99, 'Credit Card')
INTO orders(order_id, customer_id, product_id, order_date, quantity, amount, payment_method)
VALUES(50, 14, 5, TO_DATE('2024-05-09','YYYY-MM-DD'), 1, 499.99, 'Debit Card')
SELECT * FROM dual;